name: river_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-300.0.dev

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  random_name_generator: ^1.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
